# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables
ENV CELERY_BROKER_URL=redis://192.168.1.118:6379/0
ENV CELERY_RESULT_BACKEND=redis://192.168.1.118:6379/0

# Set the working directory in the container
WORKDIR /src

# Copy the current directory contents into the container at /celery
# COPY . /celery
COPY requirements-flask.txt .

# Install any needed dependencies specified in requirements.txt
RUN pip install -r requirements-flask.txt
# Run Celery
CMD celery -A tasks worker --loglevel=info
