# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set environment variables
ENV CELERY_BROKER_URL=redis://192.168.1.118:6379/0
ENV CELERY_RESULT_BACKEND=redis://192.168.1.118:6379/0

# Set the working directory in the container
WORKDIR /celery

# Copy the current directory contents into the container at /celery
COPY . /celery

# Install any needed dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run Celery
CMD celery -A myapp worker --loglevel=info
