version: '3.8'

services:
  flask:
    build: 
      context: .
      dockerfile: Dockerfile-Flask
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=src.server.start
      - FLASK_ENV=development
    
    volumes:
      - ./src:/app/src

  
