"""changed field

Revision ID: 23d73c40d4c2
Revises: 4e93564f9dc3
Create Date: 2024-02-01 20:05:55.663457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d73c40d4c2'
down_revision = '4e93564f9dc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_status', schema=None) as batch_op:
        batch_op.alter_column('timestamp_utc',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_status', schema=None) as batch_op:
        batch_op.alter_column('timestamp_utc',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
