"""odels

Revision ID: 4e93564f9dc3
Revises: 
Create Date: 2024-02-01 20:02:18.627704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e93564f9dc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time_local', sa.String(length=10), nullable=True),
    sa.Column('end_time_local', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('timezone_str', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('store_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp_utc', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_status')
    op.drop_table('store')
    op.drop_table('report')
    op.drop_table('business_hours')
    # ### end Alembic commands ###
